version: "3"

services:
  todotests:
    container_name: todotests
    build: ./todo-app/tests
    restart: always
    environment:
      - FRONT_HOST=todofrontend
    depends_on:
      - "todofront"
      - "todoback"

  todofront:
    container_name: todofrontend
    build: ./todo-app/front-end
    restart: always
    ports: 
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=ttodobackend
    depends_on:
      - "todoback"

  todoback:
    container_name: todobackend
    build: ./todo-app/back-end
    restart: always
    ports: 
      - 3001:3001
